apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --file docker-compose.yaml
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: php
  name: php
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: php
    spec:
      containers:
      - image: localhost:5000/basement/php:master
        name: php-basement
        resources: {}
        volumeMounts:
        - mountPath: /app
          name: php-claim0
      restartPolicy: Always
      volumes:
      - name: php-claim0
        persistentVolumeClaim:
          claimName: php-claim0
status: {}
