dimg: 'php'
from: 'php:7.2-fpm-alpine'
docker:
  WORKDIR: /app
  USER: app
  EXPOSE: "9000"
  ENV:
    COMPOSER_ALLOW_SUPERUSER: '1'
git:
- add: /
  to: /app
  owner: appuser
shell:
  beforeInstall:
  - addgroup -S appgroup && adduser -S appuser -G appgroup
  - apk add --no-cache freetype libpng libjpeg-turbo freetype-dev libpng-dev libjpeg-turbo-dev
  - docker-php-ext-configure gd --with-gd --with-freetype-dir=/usr/include/ --with-png-dir=/usr/include/ --with-jpeg-dir=/usr/include/
  - docker-php-ext-install -j$(nproc) gd
#  - LC_ALL=C.UTF-8 add-apt-repository -y ppa:ondrej/php
#  - apt-get update
#  - apt-get install -y php7.2 php-sqlite3 php-xml php-zip php-mbstring php-intl
  - curl -LsS https://getcomposer.org/download/1.4.1/composer.phar -o /usr/local/bin/composer
  - chmod a+x /usr/local/bin/composer
  install:
  - cd /app && composer install
  setup:
#  - "echo '#!/bin/bash' >> /app/start.sh"
#  - echo 'php bin/console server:run 0.0.0.0:8000' >> /app/start.sh
#  - echo `date` > /app/version.txt
#  - chown app:app /app/start.sh /app/version.txt
#  - chmod +x /app/start.sh
---
dimg: "nginx"
from: 'nginx:1.12-alpine'
git:
  - add: /.dapp/nginx/conf/vhost/default.conf
    to: /etc/nginx/conf.d/default.conf
#    stageDependencies:
#      install: .dapp/nginx/*
  - add: /
    to: /app
    owner: nginx
    group: nginx