version: '3'
services:
  php:
    container_name: php-basement
    build: build/php
    volumes:
    - ./:/var/www/
  nginx:
    container_name: nginx-basement
    build: build/nginx
    ports:
    - "8080:80"
    volumes:
    - ./:/var/www/
    links:
    - php