version: '3'
services:
  php:
    container_name: php-basement
    image: 'localhost:5000/symfony-demo6/php'
  nginx:
    container_name: nginx-basement
    image: 'localhost:5000/symfony-demo6/nginx'
    ports:
    - "8080:80"