apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: basement
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: basement
    spec:
      imagePullSecrets:
      - name: registry
      containers:
        # nginx
        - name: nginx-basement
          image: reg.bigln.ru/basement/nginx:master
          imagePullPolicy: Always
          ports:
          - containerPort: 80
          volumeMounts:
          - mountPath: /app/public/images
            name: basement-vol
        # php-fpm
        - name: php-basement
          image: reg.bigln.ru/basement/php:master
          imagePullPolicy: Always
          volumeMounts:
          - mountPath: /app/public/images
            name: basement-vol
      restartPolicy: Always
  volumeClaimTemplates:
    - metadata:
        name: basement-vol
        annotations:
          volume.beta.kubernetes.io/storage-class: "standard"
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: basement
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: basement